# Generated by Django 5.2.7 on 2025-10-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0002_remove_producto_proveedor_delete_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
